FROM erri120/modorganizer-base:latest

# Install OpenSSH Server 8.6.0-beta1 (https://community.chocolatey.org/packages/openssh/8.6.0-beta1)
RUN choco install openssh --version=8.6.0-beta1 -y --params "'/SSHServerFeature /AlsoLogToFile /SSHLogLevel:DEBUG2'"

# Setup OpenSSH
RUN net user docker /add \
    && net localgroup administrators docker /add \
    && powershell -Command New-Item -Type File -Path C:\ProgramData\ssh\administrators_authorized_keys; \
    Set-Acl C:\ProgramData\ssh\administrators_authorized_keys -AclObject (Get-Acl C:\ProgramData\ssh\ssh_host_dsa_key)

# OpenSSH Server
EXPOSE 22/tcp